# Generated by Django 4.1.7 on 2023-03-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_users_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
