# Generated by Django 4.1.7 on 2023-03-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userTpe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
