# Generated by Django 4.1.7 on 2023-03-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_users_usertpe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userTpe',
            new_name='userType',
        ),
    ]
